//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSaludSA.BL.WSConsultaPlanes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.saludventasonline.com/", ConfigurationName="WSConsultaPlanes.WSconsultasSoap")]
    public interface WSconsultasSoap {
        
        // CODEGEN: Generating message contract since message devolverContratosPorCedulaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.saludventasonline.com/devolverContratosPorCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaResponse devolverContratosPorCedula(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaRequest request);
        
        // CODEGEN: Generating message contract since message devolverContratosPorNumeroContratoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.saludventasonline.com/devolverContratosPorNumeroContrato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoResponse devolverContratosPorNumeroContrato(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoRequest request);
        
        // CODEGEN: Generating message contract since message devolverContratosPorContratoNpersonaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.saludventasonline.com/devolverContratosPorContratoNpersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaResponse devolverContratosPorContratoNpersona(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaRequest request);
        
        // CODEGEN: Generating message contract since message devolverContratosPorNombreApellidoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.saludventasonline.com/devolverContratosPorNombreApellido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoResponse devolverContratosPorNombreApellido(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.saludventasonline.com/")]
    public partial class Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorCedula", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorCedulaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.saludventasonline.com/")]
        public RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public string inputCedula;
        
        public devolverContratosPorCedulaRequest() {
        }
        
        public devolverContratosPorCedulaRequest(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, string inputCedula) {
            this.Autenticacion = Autenticacion;
            this.inputCedula = inputCedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorCedulaResponse", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorCedulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public string devolverContratosPorCedulaResult;
        
        public devolverContratosPorCedulaResponse() {
        }
        
        public devolverContratosPorCedulaResponse(string devolverContratosPorCedulaResult) {
            this.devolverContratosPorCedulaResult = devolverContratosPorCedulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorNumeroContrato", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorNumeroContratoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.saludventasonline.com/")]
        public RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public int inputNumeroContrato;
        
        public devolverContratosPorNumeroContratoRequest() {
        }
        
        public devolverContratosPorNumeroContratoRequest(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, int inputNumeroContrato) {
            this.Autenticacion = Autenticacion;
            this.inputNumeroContrato = inputNumeroContrato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorNumeroContratoResponse", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorNumeroContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public string devolverContratosPorNumeroContratoResult;
        
        public devolverContratosPorNumeroContratoResponse() {
        }
        
        public devolverContratosPorNumeroContratoResponse(string devolverContratosPorNumeroContratoResult) {
            this.devolverContratosPorNumeroContratoResult = devolverContratosPorNumeroContratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorContratoNpersona", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorContratoNpersonaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.saludventasonline.com/")]
        public RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public int Npersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=1)]
        public int Ncontrato;
        
        public devolverContratosPorContratoNpersonaRequest() {
        }
        
        public devolverContratosPorContratoNpersonaRequest(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, int Npersona, int Ncontrato) {
            this.Autenticacion = Autenticacion;
            this.Npersona = Npersona;
            this.Ncontrato = Ncontrato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorContratoNpersonaResponse", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorContratoNpersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public string devolverContratosPorContratoNpersonaResult;
        
        public devolverContratosPorContratoNpersonaResponse() {
        }
        
        public devolverContratosPorContratoNpersonaResponse(string devolverContratosPorContratoNpersonaResult) {
            this.devolverContratosPorContratoNpersonaResult = devolverContratosPorContratoNpersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorNombreApellido", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorNombreApellidoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.saludventasonline.com/")]
        public RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=1)]
        public string Apellido;
        
        public devolverContratosPorNombreApellidoRequest() {
        }
        
        public devolverContratosPorNombreApellidoRequest(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, string Nombre, string Apellido) {
            this.Autenticacion = Autenticacion;
            this.Nombre = Nombre;
            this.Apellido = Apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="devolverContratosPorNombreApellidoResponse", WrapperNamespace="https://www.saludventasonline.com/", IsWrapped=true)]
    public partial class devolverContratosPorNombreApellidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.saludventasonline.com/", Order=0)]
        public string devolverContratosPorNombreApellidoResult;
        
        public devolverContratosPorNombreApellidoResponse() {
        }
        
        public devolverContratosPorNombreApellidoResponse(string devolverContratosPorNombreApellidoResult) {
            this.devolverContratosPorNombreApellidoResult = devolverContratosPorNombreApellidoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSconsultasSoapChannel : RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSconsultasSoapClient : System.ServiceModel.ClientBase<RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap>, RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap {
        
        public WSconsultasSoapClient() {
        }
        
        public WSconsultasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSconsultasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSconsultasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSconsultasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaResponse RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap.devolverContratosPorCedula(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaRequest request) {
            return base.Channel.devolverContratosPorCedula(request);
        }
        
        public string devolverContratosPorCedula(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, string inputCedula) {
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaRequest inValue = new RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.inputCedula = inputCedula;
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorCedulaResponse retVal = ((RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap)(this)).devolverContratosPorCedula(inValue);
            return retVal.devolverContratosPorCedulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoResponse RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap.devolverContratosPorNumeroContrato(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoRequest request) {
            return base.Channel.devolverContratosPorNumeroContrato(request);
        }
        
        public string devolverContratosPorNumeroContrato(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, int inputNumeroContrato) {
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoRequest inValue = new RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.inputNumeroContrato = inputNumeroContrato;
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNumeroContratoResponse retVal = ((RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap)(this)).devolverContratosPorNumeroContrato(inValue);
            return retVal.devolverContratosPorNumeroContratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaResponse RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap.devolverContratosPorContratoNpersona(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaRequest request) {
            return base.Channel.devolverContratosPorContratoNpersona(request);
        }
        
        public string devolverContratosPorContratoNpersona(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, int Npersona, int Ncontrato) {
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaRequest inValue = new RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Npersona = Npersona;
            inValue.Ncontrato = Ncontrato;
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorContratoNpersonaResponse retVal = ((RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap)(this)).devolverContratosPorContratoNpersona(inValue);
            return retVal.devolverContratosPorContratoNpersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoResponse RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap.devolverContratosPorNombreApellido(RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoRequest request) {
            return base.Channel.devolverContratosPorNombreApellido(request);
        }
        
        public string devolverContratosPorNombreApellido(RedSaludSA.BL.WSConsultaPlanes.Autenticacion Autenticacion, string Nombre, string Apellido) {
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoRequest inValue = new RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoRequest();
            inValue.Autenticacion = Autenticacion;
            inValue.Nombre = Nombre;
            inValue.Apellido = Apellido;
            RedSaludSA.BL.WSConsultaPlanes.devolverContratosPorNombreApellidoResponse retVal = ((RedSaludSA.BL.WSConsultaPlanes.WSconsultasSoap)(this)).devolverContratosPorNombreApellido(inValue);
            return retVal.devolverContratosPorNombreApellidoResult;
        }
    }
}
