//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DbRedSaludsaModel", "FK_RSA_Prestador_RSA_Usuario", "RSA_Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RedSaludSA.MD.RSA_Usuario), "RSA_Prestador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedSaludSA.MD.RSA_Prestador), true)]

#endregion

namespace RedSaludSA.MD
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DbRedSaludsaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DbRedSaludsaEntities object using the connection string found in the 'DbRedSaludsaEntities' section of the application configuration file.
        /// </summary>
        public DbRedSaludsaEntities() : base("name=DbRedSaludsaEntities", "DbRedSaludsaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbRedSaludsaEntities object.
        /// </summary>
        public DbRedSaludsaEntities(string connectionString) : base(connectionString, "DbRedSaludsaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbRedSaludsaEntities object.
        /// </summary>
        public DbRedSaludsaEntities(EntityConnection connection) : base(connection, "DbRedSaludsaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RSA_Prestador> RSA_Prestador
        {
            get
            {
                if ((_RSA_Prestador == null))
                {
                    _RSA_Prestador = base.CreateObjectSet<RSA_Prestador>("RSA_Prestador");
                }
                return _RSA_Prestador;
            }
        }
        private ObjectSet<RSA_Prestador> _RSA_Prestador;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RSA_Usuario> RSA_Usuario
        {
            get
            {
                if ((_RSA_Usuario == null))
                {
                    _RSA_Usuario = base.CreateObjectSet<RSA_Usuario>("RSA_Usuario");
                }
                return _RSA_Usuario;
            }
        }
        private ObjectSet<RSA_Usuario> _RSA_Usuario;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RSA_Prestador EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRSA_Prestador(RSA_Prestador rSA_Prestador)
        {
            base.AddObject("RSA_Prestador", rSA_Prestador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RSA_Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRSA_Usuario(RSA_Usuario rSA_Usuario)
        {
            base.AddObject("RSA_Usuario", rSA_Usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbRedSaludsaModel", Name="RSA_Prestador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RSA_Prestador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RSA_Prestador object.
        /// </summary>
        /// <param name="pre_id">Initial value of the pre_id property.</param>
        /// <param name="pre_nombres">Initial value of the pre_nombres property.</param>
        /// <param name="pre_apellidos">Initial value of the pre_apellidos property.</param>
        /// <param name="pre_nivelDesde">Initial value of the pre_nivelDesde property.</param>
        /// <param name="pre_nivelHasta">Initial value of the pre_nivelHasta property.</param>
        /// <param name="usu_id">Initial value of the usu_id property.</param>
        /// <param name="pre_numeroConvenio">Initial value of the pre_numeroConvenio property.</param>
        /// <param name="pre_fechaIngreso">Initial value of the pre_fechaIngreso property.</param>
        /// <param name="pre_usuarioIngreso">Initial value of the pre_usuarioIngreso property.</param>
        public static RSA_Prestador CreateRSA_Prestador(global::System.Int32 pre_id, global::System.String pre_nombres, global::System.String pre_apellidos, global::System.Int32 pre_nivelDesde, global::System.Int32 pre_nivelHasta, global::System.Int32 usu_id, global::System.Int32 pre_numeroConvenio, global::System.DateTime pre_fechaIngreso, global::System.Int32 pre_usuarioIngreso)
        {
            RSA_Prestador rSA_Prestador = new RSA_Prestador();
            rSA_Prestador.pre_id = pre_id;
            rSA_Prestador.pre_nombres = pre_nombres;
            rSA_Prestador.pre_apellidos = pre_apellidos;
            rSA_Prestador.pre_nivelDesde = pre_nivelDesde;
            rSA_Prestador.pre_nivelHasta = pre_nivelHasta;
            rSA_Prestador.usu_id = usu_id;
            rSA_Prestador.pre_numeroConvenio = pre_numeroConvenio;
            rSA_Prestador.pre_fechaIngreso = pre_fechaIngreso;
            rSA_Prestador.pre_usuarioIngreso = pre_usuarioIngreso;
            return rSA_Prestador;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pre_id
        {
            get
            {
                return _pre_id;
            }
            set
            {
                if (_pre_id != value)
                {
                    Onpre_idChanging(value);
                    ReportPropertyChanging("pre_id");
                    _pre_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pre_id");
                    Onpre_idChanged();
                }
            }
        }
        private global::System.Int32 _pre_id;
        partial void Onpre_idChanging(global::System.Int32 value);
        partial void Onpre_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pre_nombres
        {
            get
            {
                return _pre_nombres;
            }
            set
            {
                Onpre_nombresChanging(value);
                ReportPropertyChanging("pre_nombres");
                _pre_nombres = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pre_nombres");
                Onpre_nombresChanged();
            }
        }
        private global::System.String _pre_nombres;
        partial void Onpre_nombresChanging(global::System.String value);
        partial void Onpre_nombresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pre_apellidos
        {
            get
            {
                return _pre_apellidos;
            }
            set
            {
                Onpre_apellidosChanging(value);
                ReportPropertyChanging("pre_apellidos");
                _pre_apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pre_apellidos");
                Onpre_apellidosChanged();
            }
        }
        private global::System.String _pre_apellidos;
        partial void Onpre_apellidosChanging(global::System.String value);
        partial void Onpre_apellidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pre_nivelDesde
        {
            get
            {
                return _pre_nivelDesde;
            }
            set
            {
                Onpre_nivelDesdeChanging(value);
                ReportPropertyChanging("pre_nivelDesde");
                _pre_nivelDesde = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_nivelDesde");
                Onpre_nivelDesdeChanged();
            }
        }
        private global::System.Int32 _pre_nivelDesde;
        partial void Onpre_nivelDesdeChanging(global::System.Int32 value);
        partial void Onpre_nivelDesdeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pre_nivelHasta
        {
            get
            {
                return _pre_nivelHasta;
            }
            set
            {
                Onpre_nivelHastaChanging(value);
                ReportPropertyChanging("pre_nivelHasta");
                _pre_nivelHasta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_nivelHasta");
                Onpre_nivelHastaChanged();
            }
        }
        private global::System.Int32 _pre_nivelHasta;
        partial void Onpre_nivelHastaChanging(global::System.Int32 value);
        partial void Onpre_nivelHastaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usu_id
        {
            get
            {
                return _usu_id;
            }
            set
            {
                Onusu_idChanging(value);
                ReportPropertyChanging("usu_id");
                _usu_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_id");
                Onusu_idChanged();
            }
        }
        private global::System.Int32 _usu_id;
        partial void Onusu_idChanging(global::System.Int32 value);
        partial void Onusu_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pre_ruc
        {
            get
            {
                return _pre_ruc;
            }
            set
            {
                Onpre_rucChanging(value);
                ReportPropertyChanging("pre_ruc");
                _pre_ruc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pre_ruc");
                Onpre_rucChanged();
            }
        }
        private global::System.String _pre_ruc;
        partial void Onpre_rucChanging(global::System.String value);
        partial void Onpre_rucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> pre_numeroPersona
        {
            get
            {
                return _pre_numeroPersona;
            }
            set
            {
                Onpre_numeroPersonaChanging(value);
                ReportPropertyChanging("pre_numeroPersona");
                _pre_numeroPersona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_numeroPersona");
                Onpre_numeroPersonaChanged();
            }
        }
        private Nullable<global::System.Decimal> _pre_numeroPersona;
        partial void Onpre_numeroPersonaChanging(Nullable<global::System.Decimal> value);
        partial void Onpre_numeroPersonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pre_numeroConvenio
        {
            get
            {
                return _pre_numeroConvenio;
            }
            set
            {
                Onpre_numeroConvenioChanging(value);
                ReportPropertyChanging("pre_numeroConvenio");
                _pre_numeroConvenio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_numeroConvenio");
                Onpre_numeroConvenioChanged();
            }
        }
        private global::System.Int32 _pre_numeroConvenio;
        partial void Onpre_numeroConvenioChanging(global::System.Int32 value);
        partial void Onpre_numeroConvenioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime pre_fechaIngreso
        {
            get
            {
                return _pre_fechaIngreso;
            }
            set
            {
                Onpre_fechaIngresoChanging(value);
                ReportPropertyChanging("pre_fechaIngreso");
                _pre_fechaIngreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_fechaIngreso");
                Onpre_fechaIngresoChanged();
            }
        }
        private global::System.DateTime _pre_fechaIngreso;
        partial void Onpre_fechaIngresoChanging(global::System.DateTime value);
        partial void Onpre_fechaIngresoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pre_usuarioIngreso
        {
            get
            {
                return _pre_usuarioIngreso;
            }
            set
            {
                Onpre_usuarioIngresoChanging(value);
                ReportPropertyChanging("pre_usuarioIngreso");
                _pre_usuarioIngreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_usuarioIngreso");
                Onpre_usuarioIngresoChanged();
            }
        }
        private global::System.Int32 _pre_usuarioIngreso;
        partial void Onpre_usuarioIngresoChanging(global::System.Int32 value);
        partial void Onpre_usuarioIngresoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> pre_fechaModificacion
        {
            get
            {
                return _pre_fechaModificacion;
            }
            set
            {
                Onpre_fechaModificacionChanging(value);
                ReportPropertyChanging("pre_fechaModificacion");
                _pre_fechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_fechaModificacion");
                Onpre_fechaModificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _pre_fechaModificacion;
        partial void Onpre_fechaModificacionChanging(Nullable<global::System.DateTime> value);
        partial void Onpre_fechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pre_usuarioModificacion
        {
            get
            {
                return _pre_usuarioModificacion;
            }
            set
            {
                Onpre_usuarioModificacionChanging(value);
                ReportPropertyChanging("pre_usuarioModificacion");
                _pre_usuarioModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pre_usuarioModificacion");
                Onpre_usuarioModificacionChanged();
            }
        }
        private Nullable<global::System.Int32> _pre_usuarioModificacion;
        partial void Onpre_usuarioModificacionChanging(Nullable<global::System.Int32> value);
        partial void Onpre_usuarioModificacionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbRedSaludsaModel", "FK_RSA_Prestador_RSA_Usuario", "RSA_Usuario")]
        public RSA_Usuario RSA_Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RSA_Usuario>("DbRedSaludsaModel.FK_RSA_Prestador_RSA_Usuario", "RSA_Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RSA_Usuario>("DbRedSaludsaModel.FK_RSA_Prestador_RSA_Usuario", "RSA_Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RSA_Usuario> RSA_UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RSA_Usuario>("DbRedSaludsaModel.FK_RSA_Prestador_RSA_Usuario", "RSA_Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RSA_Usuario>("DbRedSaludsaModel.FK_RSA_Prestador_RSA_Usuario", "RSA_Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbRedSaludsaModel", Name="RSA_Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RSA_Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RSA_Usuario object.
        /// </summary>
        /// <param name="usu_id">Initial value of the usu_id property.</param>
        /// <param name="usu_nombre">Initial value of the usu_nombre property.</param>
        /// <param name="usu_contrasena">Initial value of the usu_contrasena property.</param>
        /// <param name="usu_estado">Initial value of the usu_estado property.</param>
        /// <param name="usu_fechaIngreso">Initial value of the usu_fechaIngreso property.</param>
        /// <param name="usu_usuarioIngreso">Initial value of the usu_usuarioIngreso property.</param>
        public static RSA_Usuario CreateRSA_Usuario(global::System.Int32 usu_id, global::System.String usu_nombre, global::System.String usu_contrasena, global::System.String usu_estado, global::System.DateTime usu_fechaIngreso, global::System.Int32 usu_usuarioIngreso)
        {
            RSA_Usuario rSA_Usuario = new RSA_Usuario();
            rSA_Usuario.usu_id = usu_id;
            rSA_Usuario.usu_nombre = usu_nombre;
            rSA_Usuario.usu_contrasena = usu_contrasena;
            rSA_Usuario.usu_estado = usu_estado;
            rSA_Usuario.usu_fechaIngreso = usu_fechaIngreso;
            rSA_Usuario.usu_usuarioIngreso = usu_usuarioIngreso;
            return rSA_Usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usu_id
        {
            get
            {
                return _usu_id;
            }
            set
            {
                if (_usu_id != value)
                {
                    Onusu_idChanging(value);
                    ReportPropertyChanging("usu_id");
                    _usu_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usu_id");
                    Onusu_idChanged();
                }
            }
        }
        private global::System.Int32 _usu_id;
        partial void Onusu_idChanging(global::System.Int32 value);
        partial void Onusu_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usu_nombre
        {
            get
            {
                return _usu_nombre;
            }
            set
            {
                Onusu_nombreChanging(value);
                ReportPropertyChanging("usu_nombre");
                _usu_nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usu_nombre");
                Onusu_nombreChanged();
            }
        }
        private global::System.String _usu_nombre;
        partial void Onusu_nombreChanging(global::System.String value);
        partial void Onusu_nombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usu_contrasena
        {
            get
            {
                return _usu_contrasena;
            }
            set
            {
                Onusu_contrasenaChanging(value);
                ReportPropertyChanging("usu_contrasena");
                _usu_contrasena = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usu_contrasena");
                Onusu_contrasenaChanged();
            }
        }
        private global::System.String _usu_contrasena;
        partial void Onusu_contrasenaChanging(global::System.String value);
        partial void Onusu_contrasenaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usu_estado
        {
            get
            {
                return _usu_estado;
            }
            set
            {
                Onusu_estadoChanging(value);
                ReportPropertyChanging("usu_estado");
                _usu_estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usu_estado");
                Onusu_estadoChanged();
            }
        }
        private global::System.String _usu_estado;
        partial void Onusu_estadoChanging(global::System.String value);
        partial void Onusu_estadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime usu_fechaIngreso
        {
            get
            {
                return _usu_fechaIngreso;
            }
            set
            {
                Onusu_fechaIngresoChanging(value);
                ReportPropertyChanging("usu_fechaIngreso");
                _usu_fechaIngreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_fechaIngreso");
                Onusu_fechaIngresoChanged();
            }
        }
        private global::System.DateTime _usu_fechaIngreso;
        partial void Onusu_fechaIngresoChanging(global::System.DateTime value);
        partial void Onusu_fechaIngresoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usu_usuarioIngreso
        {
            get
            {
                return _usu_usuarioIngreso;
            }
            set
            {
                Onusu_usuarioIngresoChanging(value);
                ReportPropertyChanging("usu_usuarioIngreso");
                _usu_usuarioIngreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_usuarioIngreso");
                Onusu_usuarioIngresoChanged();
            }
        }
        private global::System.Int32 _usu_usuarioIngreso;
        partial void Onusu_usuarioIngresoChanging(global::System.Int32 value);
        partial void Onusu_usuarioIngresoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> usu_fechaModificacion
        {
            get
            {
                return _usu_fechaModificacion;
            }
            set
            {
                Onusu_fechaModificacionChanging(value);
                ReportPropertyChanging("usu_fechaModificacion");
                _usu_fechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_fechaModificacion");
                Onusu_fechaModificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _usu_fechaModificacion;
        partial void Onusu_fechaModificacionChanging(Nullable<global::System.DateTime> value);
        partial void Onusu_fechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usu_usuarioModificacion
        {
            get
            {
                return _usu_usuarioModificacion;
            }
            set
            {
                Onusu_usuarioModificacionChanging(value);
                ReportPropertyChanging("usu_usuarioModificacion");
                _usu_usuarioModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_usuarioModificacion");
                Onusu_usuarioModificacionChanged();
            }
        }
        private Nullable<global::System.Int32> _usu_usuarioModificacion;
        partial void Onusu_usuarioModificacionChanging(Nullable<global::System.Int32> value);
        partial void Onusu_usuarioModificacionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbRedSaludsaModel", "FK_RSA_Prestador_RSA_Usuario", "RSA_Prestador")]
        public EntityCollection<RSA_Prestador> RSA_Prestador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RSA_Prestador>("DbRedSaludsaModel.FK_RSA_Prestador_RSA_Usuario", "RSA_Prestador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RSA_Prestador>("DbRedSaludsaModel.FK_RSA_Prestador_RSA_Usuario", "RSA_Prestador", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
